# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  terragrunt: dialogue/terragrunt@1.6.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:2022.08
    steps:
      - terragrunt/install-terragrunt:
          version: '0.38.8' 

workflows:
  example-workflow:
    jobs:
      - example-job
